/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package GUI;

import Cargar_Clase.FileClassLoader;
import Estructuras_de_Datos.clsExamen;
import Estructuras_de_Datos.clsPreguntas;
import Estructuras_de_Datos.clsSeccion;
import Preguntas.Pregunta;
import java.io.File;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JDesktopPane;
import javax.swing.JFileChooser;
import javax.swing.JInternalFrame;
import javax.swing.JLabel;
import javax.swing.JList;

/**
 *
 * @author GeOrge
 */
public class frmCrearSeccion extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmCrearSeccion
     */
    
    private JDesktopPane dskPanel;
    private JLabel lblBarraEstado;
    private JList lstSecciones;
    private clsExamen insExamen;
    private clsPreguntas insPregunta;
    private clsSeccion insSeccion;
    private ArrayList<Pregunta> preguntas = new ArrayList<>();
    
    public frmCrearSeccion(Object[] args) {
        initComponents();
        dskPanel = (JDesktopPane)args[0];
        lblBarraEstado = (JLabel)args[1];
        lstSecciones = (JList)args[2];
        insExamen = (clsExamen)args[3];
        insPregunta = (clsPreguntas)args[4];
    }
    
    public frmCrearSeccion(clsSeccion seccion, Object[] args) {
        initComponents();
        txtNombre.setText(seccion.getsNombre());
        txtDescripcion.setText(seccion.getsDescripcion());
        preguntas = seccion.getAlPreguntas();
        dskPanel = (JDesktopPane)args[0];
        lblBarraEstado = (JLabel)args[1];
        insPregunta = (clsPreguntas)args[2];
        
        if(preguntas != null) {
            DefaultListModel model = new DefaultListModel();
            for(int i=0; i < preguntas.size(); i++)
                model.addElement("Pregunta");
            lstPreguntas.setModel(model);
            btnGuardar.setEnabled(true);
        }
        
    }
    
    public clsSeccion getSeccion() {
        return insSeccion;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fcArchivo = new javax.swing.JFileChooser();
        popMenu = new javax.swing.JPopupMenu();
        mnuAgregar = new javax.swing.JMenuItem();
        mnuModificar = new javax.swing.JMenuItem();
        mnuEliminar = new javax.swing.JMenuItem();
        txtNombre = new javax.swing.JTextField();
        lblNombre = new javax.swing.JLabel();
        lblDescripcionCrear = new javax.swing.JLabel();
        pnlDescScrollCrear = new javax.swing.JScrollPane();
        txtDescripcion = new javax.swing.JTextArea();
        pnlListaCrear = new javax.swing.JPanel();
        btnAgregar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstPreguntas = new javax.swing.JList();
        btnGuardar = new javax.swing.JButton();
        lblNombre1 = new javax.swing.JLabel();
        cmbTipo = new javax.swing.JComboBox();

        fcArchivo.setMultiSelectionEnabled(true);

        popMenu.setInheritsPopupMenu(true);
        popMenu.setLabel("Agregar");

        mnuAgregar.setText("Agregar");
        mnuAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAgregarActionPerformed(evt);
            }
        });
        popMenu.add(mnuAgregar);

        mnuModificar.setText("Modificar");
        mnuModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuModificarActionPerformed(evt);
            }
        });
        popMenu.add(mnuModificar);

        mnuEliminar.setText("Eliminar");
        mnuEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuEliminarActionPerformed(evt);
            }
        });
        popMenu.add(mnuEliminar);

        setClosable(true);
        setResizable(true);
        setTitle("Nueva Sección");
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNombreKeyReleased(evt);
            }
        });

        lblNombre.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        lblNombre.setText("Nombre:");

        lblDescripcionCrear.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        lblDescripcionCrear.setText("Descripción:");

        txtDescripcion.setColumns(20);
        txtDescripcion.setRows(3);
        txtDescripcion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDescripcionKeyReleased(evt);
            }
        });
        pnlDescScrollCrear.setViewportView(txtDescripcion);

        pnlListaCrear.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Preguntas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(0, 102, 255))); // NOI18N
        pnlListaCrear.setMaximumSize(new java.awt.Dimension(270, 184));
        pnlListaCrear.setMinimumSize(new java.awt.Dimension(270, 184));
        pnlListaCrear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlListaCrearMouseEntered(evt);
            }
        });

        btnAgregar.setBackground(new java.awt.Color(255, 255, 255));
        btnAgregar.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        lstPreguntas.setComponentPopupMenu(popMenu);
        lstPreguntas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lstPreguntasMouseEntered(evt);
            }
        });
        jScrollPane1.setViewportView(lstPreguntas);

        javax.swing.GroupLayout pnlListaCrearLayout = new javax.swing.GroupLayout(pnlListaCrear);
        pnlListaCrear.setLayout(pnlListaCrearLayout);
        pnlListaCrearLayout.setHorizontalGroup(
            pnlListaCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlListaCrearLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlListaCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlListaCrearLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnAgregar))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        pnlListaCrearLayout.setVerticalGroup(
            pnlListaCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlListaCrearLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                .addGap(10, 10, 10)
                .addComponent(btnAgregar)
                .addGap(10, 10, 10))
        );

        btnGuardar.setBackground(new java.awt.Color(255, 255, 255));
        btnGuardar.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.setEnabled(false);
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        lblNombre1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        lblNombre1.setText("Tipo:");

        cmbTipo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Cargar..." }));
        cmbTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTipoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnGuardar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDescripcionCrear)
                    .addComponent(pnlDescScrollCrear)
                    .addComponent(pnlListaCrear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblNombre)
                        .addGap(10, 10, 10)
                        .addComponent(txtNombre))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblNombre1)
                        .addGap(10, 10, 10)
                        .addComponent(cmbTipo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombre)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addComponent(lblDescripcionCrear)
                .addGap(5, 5, 5)
                .addComponent(pnlDescScrollCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombre1)
                    .addComponent(cmbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(pnlListaCrear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(btnGuardar)
                .addGap(10, 10, 10))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        try {
            Class cClase = insPregunta.getPreguntas().get(cmbTipo.getSelectedIndex());
            JInternalFrame frame = (JInternalFrame) cClase.newInstance();
            dskPanel.add(frame);
            ((Pregunta) frame).insertarInfo();
            frame.setTitle(frame.getTitle() + " Nueva Pregunta");
            frame.pack();
            preguntas.add((Pregunta)frame);
            
            DefaultListModel model = new DefaultListModel();
            for(int i=0; i < lstPreguntas.getModel().getSize() ; i++)
                model.addElement(lstPreguntas.getModel().getElementAt(i));
            model.addElement("Pregunta");
            lstPreguntas.setModel(model);
        } catch (InstantiationException ex) {
        } catch (IllegalAccessException ex) {
        }
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        if(insExamen != null) {
            insSeccion = new clsSeccion(txtNombre.getText(), txtDescripcion.getText());
            insSeccion.setAlPreguntas(preguntas);
            insExamen.addSeccion(insSeccion);

            DefaultListModel model = new DefaultListModel();
            for(int i=0; i < lstSecciones.getModel().getSize() ; i++)
                model.addElement(lstSecciones.getModel().getElementAt(i));
            model.addElement(txtNombre.getText());
            lstSecciones.setModel(model);
        }
        this.dispose();
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        this.setLocation(600, 40);
        txtDescripcion.setLineWrap(true);
        ArrayList<Class> lcLista = insPregunta.getPreguntas();
        if(lcLista.size() != 0) {
            for(int i=lcLista.size()-1; i >= 0; i--) 
                cmbTipo.insertItemAt(lcLista.get(i).getName().substring(10), 0);
        }
    }//GEN-LAST:event_formComponentShown

    private void txtNombreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyReleased
        if(!txtNombre.getText().equals("") && 
           !txtDescripcion.getText().equals(""))
            btnGuardar.setEnabled(true);
        else
            btnGuardar.setEnabled(false);
    }//GEN-LAST:event_txtNombreKeyReleased

    private void txtDescripcionKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDescripcionKeyReleased
        if(!txtNombre.getText().equals("") && 
           !txtDescripcion.getText().equals(""))
            btnGuardar.setEnabled(true);
        else
            btnGuardar.setEnabled(false);
    }//GEN-LAST:event_txtDescripcionKeyReleased

    private void pnlListaCrearMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlListaCrearMouseEntered
        lblBarraEstado.setText("");
    }//GEN-LAST:event_pnlListaCrearMouseEntered

    private void cmbTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTipoActionPerformed
        if(cmbTipo.getSelectedItem().toString().equals("Cargar...")) {
            FileClassLoader fcCargar = new FileClassLoader(".");
            try{ 
                if (fcArchivo.showOpenDialog(null) == JFileChooser.APPROVE_OPTION) {
                    Class cClase = null;
                    File[] fArchivos = fcArchivo.getSelectedFiles();
                    for (int i = 0; i < fArchivos.length; i++)
                        cClase = fcCargar.loadClass1(fArchivos[i], true);
                    
                    ArrayList<Class> lcLista = insPregunta.getPreguntas();
                    boolean bTemp = true;
                    for(int i=0; i < lcLista.size(); i++) {
                        if(lcLista.get(i).getName().equals(cClase.getName()))
                            bTemp = false;
                    }
                    if(bTemp) {
                        insPregunta.addPregunta(cClase);
                        cmbTipo.insertItemAt(cClase.getName().substring(10), 0);
                    }
                }
            } catch (ClassNotFoundException ex) { }
        }
    }//GEN-LAST:event_cmbTipoActionPerformed

    private void mnuAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAgregarActionPerformed
        try {
            Class cClase = insPregunta.getPreguntas().get(cmbTipo.getSelectedIndex());
            JInternalFrame frame = (JInternalFrame) cClase.newInstance();
            dskPanel.add(frame);
            ((Pregunta) frame).insertarInfo();
            frame.setTitle(frame.getTitle() + " Nueva Pregunta");
            frame.pack();
            preguntas.add((Pregunta)frame);
            DefaultListModel model = new DefaultListModel();
            for(int i=0; i < lstPreguntas.getModel().getSize() ; i++)
                model.addElement(lstPreguntas.getModel().getElementAt(i));
            model.addElement("Pregunta");
            lstPreguntas.setModel(model);
        } catch (InstantiationException ex) {
        } catch (IllegalAccessException ex) {
        }
    }//GEN-LAST:event_mnuAgregarActionPerformed

    private void lstPreguntasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstPreguntasMouseEntered
        lblBarraEstado.setText("Click derecho para mas opciones");
    }//GEN-LAST:event_lstPreguntasMouseEntered

    private void mnuModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuModificarActionPerformed
        JInternalFrame frame = (JInternalFrame)preguntas.get(lstPreguntas.getSelectedIndex());
        dskPanel.add(frame);
        ((Pregunta) frame).insertarInfo();
        frame.pack();
    }//GEN-LAST:event_mnuModificarActionPerformed

    private void mnuEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuEliminarActionPerformed
        DefaultListModel model = (DefaultListModel) lstPreguntas.getModel();
        int selectedIndex = lstPreguntas.getSelectedIndex();
        if (selectedIndex >= 0 && selectedIndex < model.getSize()) 
            model.remove(selectedIndex);
        preguntas.remove(selectedIndex);
    }//GEN-LAST:event_mnuEliminarActionPerformed

    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JComboBox cmbTipo;
    private javax.swing.JFileChooser fcArchivo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDescripcionCrear;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblNombre1;
    private javax.swing.JList lstPreguntas;
    private javax.swing.JMenuItem mnuAgregar;
    private javax.swing.JMenuItem mnuEliminar;
    private javax.swing.JMenuItem mnuModificar;
    private javax.swing.JScrollPane pnlDescScrollCrear;
    private javax.swing.JPanel pnlListaCrear;
    private javax.swing.JPopupMenu popMenu;
    private javax.swing.JTextArea txtDescripcion;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
