/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package GUI;

import Estructuras_de_Datos.clsExamen;
import Estructuras_de_Datos.clsPreguntas;
import Estructuras_de_Datos.clsSeccion;
import Preguntas.Pregunta;
import java.io.File;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDesktopPane;
import javax.swing.JFileChooser;
import javax.swing.JInternalFrame;
import javax.swing.JLabel;
import javax.swing.JList;

/**
 *
 * @author GeOrge
 */
public class frmCrearSeccion extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmCrearSeccion
     */
    
    JDesktopPane dskPanel;
    JLabel lblBarraEstado;
    JList lstSecciones;
    clsExamen insExamen;
    clsPreguntas insPregunta = new clsPreguntas();
    
    public frmCrearSeccion(Object[] args) {
        initComponents();
        dskPanel = (JDesktopPane)args[0];
        lblBarraEstado = (JLabel)args[1];
        lstSecciones = (JList)args[2];
        insExamen = (clsExamen)args[3];
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fcArchivo = new javax.swing.JFileChooser();
        popMenu = new javax.swing.JPopupMenu();
        mnuAgregar = new javax.swing.JMenuItem();
        mnuModificar = new javax.swing.JMenuItem();
        mnuEliminar = new javax.swing.JMenuItem();
        txtNombre = new javax.swing.JTextField();
        lblNombre = new javax.swing.JLabel();
        lblDescripcionCrear = new javax.swing.JLabel();
        pnlDescScrollCrear = new javax.swing.JScrollPane();
        txtDescripcion = new javax.swing.JTextArea();
        pnlListaCrear = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstPreguntas = new javax.swing.JList();
        btnAgregar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        lblNombre1 = new javax.swing.JLabel();
        cmbTipo = new javax.swing.JComboBox();

        fcArchivo.setMultiSelectionEnabled(true);

        popMenu.setInheritsPopupMenu(true);
        popMenu.setLabel("Agregar");

        mnuAgregar.setText("Agregar");
        popMenu.add(mnuAgregar);

        mnuModificar.setText("jMenuItem1");
        popMenu.add(mnuModificar);

        mnuEliminar.setText("jMenuItem2");
        popMenu.add(mnuEliminar);

        setClosable(true);
        setTitle("Nueva Sección");
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNombreKeyReleased(evt);
            }
        });

        lblNombre.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        lblNombre.setText("Nombre:");

        lblDescripcionCrear.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        lblDescripcionCrear.setText("Descripción:");

        txtDescripcion.setColumns(20);
        txtDescripcion.setRows(3);
        txtDescripcion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDescripcionKeyReleased(evt);
            }
        });
        pnlDescScrollCrear.setViewportView(txtDescripcion);

        pnlListaCrear.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Preguntas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, new java.awt.Color(0, 102, 255)));
        pnlListaCrear.setMaximumSize(new java.awt.Dimension(270, 184));
        pnlListaCrear.setMinimumSize(new java.awt.Dimension(270, 184));
        pnlListaCrear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlListaCrearMouseEntered(evt);
            }
        });

        lstPreguntas.setComponentPopupMenu(popMenu);
        lstPreguntas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstPreguntasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lstPreguntasMouseEntered(evt);
            }
        });
        jScrollPane2.setViewportView(lstPreguntas);

        btnAgregar.setBackground(new java.awt.Color(255, 255, 255));
        btnAgregar.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlListaCrearLayout = new javax.swing.GroupLayout(pnlListaCrear);
        pnlListaCrear.setLayout(pnlListaCrearLayout);
        pnlListaCrearLayout.setHorizontalGroup(
            pnlListaCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlListaCrearLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(pnlListaCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlListaCrearLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnAgregar)))
                .addContainerGap())
        );
        pnlListaCrearLayout.setVerticalGroup(
            pnlListaCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlListaCrearLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(btnAgregar)
                .addGap(10, 10, 10))
        );

        btnGuardar.setBackground(new java.awt.Color(255, 255, 255));
        btnGuardar.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.setEnabled(false);
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        lblNombre1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        lblNombre1.setText("Tipo:");

        cmbTipo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Cargar..." }));
        cmbTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTipoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnGuardar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDescripcionCrear)
                    .addComponent(pnlDescScrollCrear, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
                    .addComponent(pnlListaCrear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblNombre)
                        .addGap(10, 10, 10)
                        .addComponent(txtNombre))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblNombre1)
                        .addGap(10, 10, 10)
                        .addComponent(cmbTipo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombre)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addComponent(lblDescripcionCrear)
                .addGap(5, 5, 5)
                .addComponent(pnlDescScrollCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombre1)
                    .addComponent(cmbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(pnlListaCrear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(btnGuardar)
                .addGap(10, 10, 10))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed

    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        insExamen.addSeccion(new clsSeccion(txtNombre.getText(), txtDescripcion.getText()));
        clsVentana insVentana = new clsVentana();
        lstSecciones.setModel(insVentana.setItems(insExamen.getAlSecciones().toArray()));
        this.dispose();
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        this.setLocation(600, 40);
        txtDescripcion.setLineWrap(true);
    }//GEN-LAST:event_formComponentShown

    private void lstPreguntasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstPreguntasMouseEntered
        lblBarraEstado.setText("Click derecho para agregar una pregunta");
    }//GEN-LAST:event_lstPreguntasMouseEntered

    private void txtNombreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyReleased
        clsVentana ventana = new clsVentana();
        if(ventana.activarBoton(new String[]{txtNombre.getText(), txtDescripcion.getText()}))
            btnGuardar.setEnabled(true);
        else
            btnGuardar.setEnabled(false);
    }//GEN-LAST:event_txtNombreKeyReleased

    private void txtDescripcionKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDescripcionKeyReleased
        clsVentana ventana = new clsVentana();
        if(ventana.activarBoton(new String[]{txtNombre.getText(), txtDescripcion.getText()}))
            btnGuardar.setEnabled(true);
        else
            btnGuardar.setEnabled(false);
    }//GEN-LAST:event_txtDescripcionKeyReleased

    private void pnlListaCrearMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlListaCrearMouseEntered
        lblBarraEstado.setText("");
    }//GEN-LAST:event_pnlListaCrearMouseEntered

    private void cmbTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTipoActionPerformed
        if(cmbTipo.getSelectedItem().toString().equals("Cargar...")) {
            FileClassLoader fcCargar = new FileClassLoader(".");
            try{ 
                if (fcArchivo.showOpenDialog(null) == JFileChooser.APPROVE_OPTION) {
                    Class cClase = null;
                    File[] fArchivos = fcArchivo.getSelectedFiles();
                    for (int i = 0; i < fArchivos.length; i++)
                        cClase = fcCargar.loadClass1(fArchivos[i], true);
                    
                    
                    ArrayList<Class> lcLista = insPregunta.getPreguntas();
                    boolean bTemp = true;
                    for(int i=0; i < lcLista.size(); i++) {
                        if(lcLista.get(i).equals(cClase))
                            bTemp = false;
                    }
                    if(bTemp) {
                        insPregunta.addPregunta(cClase);
                        cmbTipo.insertItemAt(cClase.getName().substring(10), 0);
//                        try {
//                            JInternalFrame frame = (JInternalFrame) cClase.newInstance();
//                            dskPanel.add(frame);
//                            ((Pregunta) frame).insertarInfo();
//                            frame.setTitle(frame.getTitle()+" Nueva Pregunta");
//                            frame.pack();
//                        } catch (InstantiationException ex) {
//                        } catch (IllegalAccessException ex) { }
                    }
                }
            } catch (ClassNotFoundException ex) { }
        }
    }//GEN-LAST:event_cmbTipoActionPerformed

    private void lstPreguntasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstPreguntasMouseClicked
        
    }//GEN-LAST:event_lstPreguntasMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JComboBox cmbTipo;
    private javax.swing.JFileChooser fcArchivo;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblDescripcionCrear;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblNombre1;
    private javax.swing.JList lstPreguntas;
    private javax.swing.JMenuItem mnuAgregar;
    private javax.swing.JMenuItem mnuEliminar;
    private javax.swing.JMenuItem mnuModificar;
    private javax.swing.JScrollPane pnlDescScrollCrear;
    private javax.swing.JPanel pnlListaCrear;
    private javax.swing.JPopupMenu popMenu;
    private javax.swing.JTextArea txtDescripcion;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
