/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package GUI;
import Estructuras_de_Datos.*;
import javax.swing.DefaultListModel;
import javax.swing.JInternalFrame;
import GUI.*;
import Preguntas.SeleccionUnica;
import javax.swing.JDesktopPane;

/**
 *
 * @author jdbr
 */
public class frmListaExamen extends javax.swing.JInternalFrame {

    clsExamenes examenes = new clsExamenes();
    DefaultListModel modelo = new DefaultListModel();
    JDesktopPane dskPanel;
    
    /**
     * Creates new form frmListaExamen
     */
    public frmListaExamen(Object arg) {
        initComponents();
        dskPanel = (JDesktopPane)arg;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jListExamenes = new javax.swing.JList();
        jButton1 = new javax.swing.JButton();

        setClosable(true);
        setTitle("Lista de Examenes");
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jScrollPane1.setViewportView(jListExamenes);

        jButton1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton1.setText("Inicio");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        this.setLocation(500, 50);
        
        clsExamen exa1=new clsExamen();
        clsExamen exa2=new clsExamen();
        clsExamen exa3=new clsExamen();
        exa1.setsNombre("Investigacion de Operaciones");
        
        exa1.setsDescripcion("Todas estas preguntas tienen sus respuestas en el manual entregado de ejercicios. Lo mínimo que deben hacer es buscar en dicho documento la respuesta adecuada. Simplemente marquen en el mismo texto la respuesta y me envían el archivo en formato PDF al correo gerardo.brenes@gbsys.com con el asunto: Examen 2 y su nombre. O me envían un correo con solo las respuestas. Es INDIVIDUAL. Fecha/hora límite para el correo: Viernes 8/11/2013:12MD");
        exa1.setdFecha("03/10/2013");
        exa1.setiTotalPuntos(60);
        exa1.setsProfesor("Oscar Viquez");
        clsSeccion sec1= new clsSeccion("Seleccion Unica","Selecione la respuesta correcta");
        sec1.setiTotalPuntos(10);
        SeleccionUnica preg1 =new SeleccionUnica();
        preg1.insertarInfo();
        clsSeccion sec2= new clsSeccion("Seleccion Multiple","Selecione la/s respuesta correcta/s");
        sec2.setiTotalPuntos(25);
        clsSeccion sec3= new clsSeccion("Complete","Complete la frase");
        sec3.setiTotalPuntos(30);
        exa1.addSeccion(sec1);
        exa1.addSeccion(sec2);
        exa1.addSeccion(sec3);
        
        examenes.agregarExamen(exa1);
        
        for (clsExamen exa : examenes.getExamenes()){
            modelo.addElement(exa.getsNombre());            
        }
        jListExamenes.setModel(modelo);
        
    }//GEN-LAST:event_formComponentShown

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        clsExamen insExamen = examenes.getExamenes().get(jListExamenes.getSelectedIndex());
        JInternalFrame frame = new frmExamen(new Object[]{insExamen, dskPanel});
        frame.setVisible(true);
        
        frame.setTitle(examenes.getExamenes().get(jListExamenes.getSelectedIndex()).getiNumeroExamen()+"° Examen");
 
        dskPanel.add(frame);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JList jListExamenes;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
